# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: pip install -r requirements.txt

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview

vscode:
  extensions:
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - ms-toolsai.jupyter
    - ms-python.python
    - sonarsource.sonarlint-vscode